### ISSUE TITLE
Return alert UUID in annotations

### ISSUE THREAD

**Issue by torbenaa** [VolkovLabs/volkovlabs-grapi-datasource#18]
To allow deep linking to alert rules in grafana, could you please add the UUID field in the annotation list for alert ?

**Comment by mikhail-vl** [comment]
@torbenaa There is no UUID in the Alerts returned from API. There is only Alert Id.

```
{
    "id": 3,
    "alertId": 1,
    "alertName": "",
    "dashboardId": 2,
    "dashboardUID": "Rcb6nob4k",
    "panelId": 2,
    "userId": 0,
    "newState": "Alerting",
    "prevState": "Pending",
    "created": 1679214840079,
    "updated": 1679214840079,
    "time": 1679214840000,
    "timeEnd": 1679214840000,
    "text": "Metrics {alertname=Metrics, grafana_folder=Test, name=test} - A=123.000000, B=123.000000, C=1.000000",
    "tags": [],
    "login": "",
    "email": "",
    "avatarUrl": "",
    "data": {
        "values": {
            "A": 123,
            "B": 123,
            "C": 1
        }
    }
}
```

**Comment by mikhail-vl** [comment]
Could you please provide more details what you are trying to do?

**Comment by torbenaa** [comment]
Basically, I would love to create a dashboard with alert history for a given period with links to the alert rule ( i.e. /alerting/grafana/<uuid>/view

You are right : The endpoint /api/annotations?limit=100&&type=alert does not give me the uuid. But that can probably be looked up in /api/v1/provisioning/alert-rules

Maybe there is a better way to get this ?

Thank you for your great work !

BR Torben

**Comment by mikhail-vl** [comment]
@torbenaa I can add Provisioned Alert Rules. Then both can be retrieved in separate queries and combined using Transformations using Alert Id.

  I will look into it later today.

**Comment by torbenaa** [comment]
That is great, Mikael. This plugin has great potential :)

Thanks a lot !

**Comment by mikhail-vl** [comment]
@torbenaa Thank you, we are planning to support most HTTP API endpoints. You are welcome to open a feature request if you need anything else.

  I will merge it later today, and you can test it using CI signed artifact.

**Comment by mikhail-vl** [comment]
@torbenaa Merge by Field Transformation support only merge by Time fields and did not work to merge by Alarm Id.

  We added two additional fields for Name (Title) and UID. You can test using CI artifact: https://github.com/VolkovLabs/volkovlabs-grapi-datasource/actions/runs/4462197411

  Let me know if there is anything else.

**Comment by torbenaa** [comment]
Works perfectly ! Thanks again :)

**Comment by mikhail-vl** [comment]
@torbenaa Thank you for confirming. We will add more features and will release a new version later this week.
