### ISSUE TITLE
Can grapi-datasource be used to get number of instances of multidimensional alerts

### ISSUE THREAD

**Issue by alespour** [VolkovLabs/volkovlabs-grapi-datasource#37]
Can grapi-datasource be used to find number of instances of multidimensional alerts, please? Standard Alert list panel shows number of rules at selected state(s), but I need to show number of alert instances.

I'm able to list alerts annotations in a table (many thanks to Daria's video!), but have no idea if/how I can recognize records are currently active instances of an alert and count them.
Thank you!

**Comment by alespour** [comment]
Thank you for the response.

I tried to play directly with HTTP API a little, but not with much success. `/api/alertmanager/grafana/api/v2/alerts` returns list of alert instances, but only in Alerting state. I would also like Pending state.

Alert list panel in List mode shows nicely, how many instances of alerts are there per rule [1]. But - no transformations are supported, it's a very specialized panel with almost no customization. It provides good grouping and filtering options, but the same can be achieved with transformations as available in most panels.

The use case is I need to show on dashboard number of alert instances for all alert rules. Eg. if there were multiple devices monitor excessive temperature, low lightning etc -> multiple series of various metrics crossing thresholds -> multiple alert instances for multiple rules. 

So if grapi-datasource could be used to list **current** (or active - not sure how to call it)  alert instances like Alert list panel does, it would be great. The already existing _new state_ choice All, Normal, Pending, Alerting is fine, I could group the result and modify via transformations as necessary, and display. eg. how many devices are reporting excessive temperature etc.

[1]
![image](https://user-images.githubusercontent.com/42931850/233668509-4061ebd7-6e1b-4f81-8383-626d700d899f.png)

**Comment by mikhail-vl** [comment]
@alespour Can you use Alert labels to count a number of instances using Transformations?

  We added field `filters` which can be used to extract instance names: https://volkovlabs.io/blog/grapi-datasource-1.2.0-20230331/#alert-labels

**Comment by alespour** [comment]
@mikhail-vl But the problem is that the list contains older alert instances that are no loner active. Right at this moment, Grafana's Alert list and also Alert Rules shows 4 firing rules, each with 1 alert instance. But table panel that uses grapi-datasource shows 10 records with New State = Alerting. There are records in the list that represents alert instances that occurred earlier today.


Maybe I'm using the ds in a wrong way? 

![image](https://user-images.githubusercontent.com/42931850/233710453-75cbf4a2-42b0-4f2d-8812-781b3084ad9c.png)

**Comment by mikhail-vl** [comment]
@alespour You are doing great! I am trying to understand your requirements and learning along the way.

  If we add a new field indicating the alert is current (firing), will it work for you? Then we will cover the functionality of the Alert List panel. I can see how the panel checks that the alert is current to display it.

**Comment by alespour** [comment]
That would be great. I tried to find out how the Alert List panel does it, but hell it is too complicated code for me :)
Thank you!

**Comment by mikhail-vl** [comment]
@alespour Cool, I will try to take a look over the weekend or earlier next week.
