### ISSUE TITLE
Grafana HTTP API not loading Alerts/Annotations correctly

### ISSUE THREAD

**Issue by centenico** [VolkovLabs/volkovlabs-grapi-datasource#38]
Good morning, I'm having some issue displaying all my Grafana alerts/annotations correctly with the Grafana HTTP API data source.
I've installed it and connected it with my token correctly, and in fact some of the panel (the two showing the infos/health status) work correctly, but the Annotations panel doesn't seems to be working and give me the following error:

![image](https://user-images.githubusercontent.com/13175203/235905148-a920ad90-6a09-4615-b4f0-b999c423183e.png)

What could be possibly causing this error?

Grafana HTTP API version: 1.2.0
Grafana version: 9.3.8
Main Data-source: Prometheus

![image](https://user-images.githubusercontent.com/13175203/235941460-a6f0c783-d739-45ff-970f-2685f414877c.png)

Thanks a lot!

**Comment by mikhail-vl** [comment]
@centenico Are you using Unified Alerting? Do you use a token with Viewer, Editor, or Admin permissions?

  The Alert rules endpoint is used to get an Alert UID. If it's not found, then it's not a unified alerting or permissions issue.
  I will take a look to see which one is it and will handle it.

**Comment by centenico** [comment]
Hi @mikhail-vl thanks for answering, I'm using a token with Editor permissions, but I've also tried with Admin.
I think that yes, I'm using Unified Alerting but I'll leave you a bunch of screenshots and configurations to give you the most possible informations about my system/alert setup. Hope that'll be useful.

I've also tried logging the alerts via one apachEcharts with the following line:
_console.log(data.annotations);_
which returns an empty array.

-  We're using prometheus as a datasource for our data.
- Prometheus datasource has a setting for Alerting "Manage alerts via Alerting UI" which is enabled.
-  I've tried generating alerts with and without an Alert ID (with a random number)
- The AlertManager in the Alerting -> Admin configuration is set and locked to "Grafana"
- I've tried enabling the "Internal and External" setting in "Send alerts to" configuration


![image](https://user-images.githubusercontent.com/13175203/236149401-aafcc755-f200-42b0-b450-966fa073b143.png)
![image](https://user-images.githubusercontent.com/13175203/236149800-ab18a6d6-242e-4b61-aacf-df28e7f9b2eb.png)

**Comment by centenico** [comment]
@mikhail-vl Hi, I've partly solved my issue, as I was having an older version of Grafana, which was missing some APIs, now the panels doens't give me error anymore, although I am still not seeing my alerts listed.

**Comment by mikhail-vl** [comment]
@centenico Thank you for confirming, then it makes sense to handle the `not found` error for the older versions.

**Comment by mikhail-vl** [comment]
@centenico I Appreciate the help. I added Exception Handling for the Alert Rules to support older versions of Grafana and removed Admin/Editor restrictions to retrieve Annotations.

  Now Viewer permissions are enough, but you won't see the Alert name or UID.
  You can download the latest CI artifact to test before the official build: https://github.com/VolkovLabs/volkovlabs-grapi-datasource/actions/workflows/ci.yml
