### ISSUE TITLE
[question] not found (404) error

### ISSUE THREAD

**Issue by muf** [VolkovLabs/volkovlabs-grapi-datasource#49]
hello, I installed grafana oss 8.5.13 version and then installed "HTTP API plugin".

After that, i created new data source like this. (request for https://dummyjson.com/products/1)
> <img width="1562" alt="image" src="https://github.com/VolkovLabs/volkovlabs-grapi-datasource/assets/7663124/a5e41975-ef8e-46d2-88ea-d5275f9b6803">

- create api key 
<img width="1618" alt="image" src="https://github.com/VolkovLabs/volkovlabs-grapi-datasource/assets/7663124/803a5193-6d7b-4864-a4a4-9dfe34abd362">
- copy key and paste to Token field
<img width="1686" alt="image" src="https://github.com/VolkovLabs/volkovlabs-grapi-datasource/assets/7663124/5729f4d5-da88-43ad-be84-968e14d8be60">

But still not working.. Is there any steps that i missed?
Is there anything wrong for those steps?

<img width="1159" alt="image" src="https://github.com/VolkovLabs/volkovlabs-grapi-datasource/assets/7663124/98447889-dee5-4b80-80c8-8a5e00ad5fec">

**Comment by mikhail-vl** [comment]
@muf Grafana HTTP API data source designed to connect to Grafana HTTP API, not any other REST API.

  For REST API, you can use JSON or Infinity data source: https://www.youtube.com/watch?v=h1Mx4UvtKGY
