### ISSUE TITLE
Error. Not able connect.

### ISSUE THREAD

**Issue by jsarnowski96** [VolkovLabs/volkovlabs-grapi-datasource#58]
I've just installed plugin and wanted to create a data source, however no matter which method I try (local or remote request mode), I'm getting this ambiguous error.

After looking into grafana's logs I found this entry:

`skip committing the transaction because it belongs to a session created in the outer scope`

as well as

`Applying default URL parsing for this data source type" type=volkovlabs-grapi-datasource url=`
`Data source URL doesn't specify protocol, so prepending it with http:// in order to make it unambiguous" type=volkovlabs-grapi-datasource url=`
where url is not set in both cases

**Comment by mikhail-vl** [comment]
@jsarnowski96 What is your version of Grafana?

  I will check this error for the local mode, which does not require it.
  The remove mode requires URL and Token to connect as we described in the documentation: https://volkovlabs.io/plugins/volkovlabs-grapi-datasource/configuration/

**Comment by jsarnowski96** [comment]
In remote reuqest mode I tried both public https://grafana-instance domain as well as http://localhost:3000 with service account's token.

DS is being saved everytime, but it is unable to connect to Grafana API.

**Comment by jsarnowski96** [comment]
@mikhail-vl we are using Grafana **10.1.5** version

**Comment by jsarnowski96** [comment]
I might try using Editor-level token, maybe that's the root cause.

**Comment by mikhail-vl** [comment]
@jsarnowski96 We tested on 10.1.5 and it should work as expected in both modes.

  Viewer token is enough to connect and display Annotations.

**Comment by mikhail-vl** [comment]
Do you see any errors in the Browser's Console or Network tabs?

**Comment by jsarnowski96** [comment]
@mikhail-vl nothing at all.

**Comment by jsarnowski96** [comment]
taken from DS JSON config:
`"routes": [
                    {
                        "path": "api",
                        "method": "GET",
                        "reqRole": "Viewer",
                        "url": "{{ .JsonData.url }}/api",
                        "urlParams": null,
                        "headers": [
                            {
                                "name": "Authorization",
                                "content": "Bearer {{ .SecureJsonData.token }}"
                            }
                        ],
                        "authType": "",
                        "tokenAuth": null,
                        "jwtTokenAuth": null,
                        "body": null
                    }
                ],`

**Comment by mikhail-vl** [comment]
@jsarnowski96 When we test Data Source health, we do `/api/health` and `/api/org` to retrieve version and organization name.
  One of them should be missing, this is why it's failed to do the health check.
  Could you check the preview of `org` and `health` requests to see what is returned.

```
    /**
     * Check Health
     */
    const health = await this.api.features.health.get();
    const org = await this.api.features.org.get();

    /**
     * Connected
     */
    if (health?.version && org?.name) {
      return {
        status: DataSourceTestStatus.SUCCESS,
        message: `${Messages.connectedToOrg} ${org.name}. ${Messages.version} ${health.version}`,
      };
    }
```

**Comment by jsarnowski96** [comment]
@mikhail-vl API requests return correct org ID and OK DB status

**Comment by asimonok** [comment]
Tested on Grafana `v11.2.0`. Works as expected with remote url and service token with a view access.

Please let us know if the issue still exists for you
